# Generated by Django 4.0.1 on 2022-04-03 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default=0, max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_final', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Noteitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_final', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notekey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notekey', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notetype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CO',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='note.note')),
                ('typ', models.CharField(max_length=10)),
            ],
            bases=('note.note',),
        ),
        migrations.CreateModel(
            name='COItem',
            fields=[
                ('noteitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='note.noteitem')),
                ('typ', models.CharField(max_length=10)),
            ],
            bases=('note.noteitem',),
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='note.note')),
                ('typ', models.CharField(max_length=10)),
            ],
            bases=('note.note',),
        ),
        migrations.CreateModel(
            name='POItem',
            fields=[
                ('noteitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='note.noteitem')),
                ('typ', models.CharField(max_length=10)),
            ],
            bases=('note.noteitem',),
        ),
        migrations.CreateModel(
            name='SO',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='note.note')),
                ('typ', models.CharField(max_length=10)),
            ],
            bases=('note.note',),
        ),
        migrations.CreateModel(
            name='SOItem',
            fields=[
                ('noteitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='note.noteitem')),
                ('typ', models.CharField(max_length=10)),
            ],
            bases=('note.noteitem',),
        ),
        migrations.CreateModel(
            name='WO',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='note.note')),
                ('typ', models.CharField(max_length=10)),
            ],
            bases=('note.note',),
        ),
        migrations.CreateModel(
            name='WOItem',
            fields=[
                ('noteitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='note.noteitem')),
                ('typ', models.CharField(max_length=10)),
            ],
            bases=('note.noteitem',),
        ),
        migrations.CreateModel(
            name='Noteitemkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteitemkey', models.CharField(max_length=25)),
                ('notekey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notekeys', to='note.notekey')),
            ],
        ),
        migrations.AddField(
            model_name='noteitem',
            name='noteitemkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='note.noteitemkey'),
        ),
        migrations.AddField(
            model_name='noteitem',
            name='notekey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='note.notekey'),
        ),
        migrations.AddField(
            model_name='noteitem',
            name='notetypekey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notetypes', to='note.notetype'),
        ),
        migrations.AddField(
            model_name='noteitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='note.product'),
        ),
        migrations.AddField(
            model_name='note',
            name='notekey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='note.notekey'),
        ),
        migrations.AddField(
            model_name='note',
            name='notetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='note.notetype'),
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='note.status'),
        ),
        migrations.CreateModel(
            name='InvControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='note.inv')),
                ('noteitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='note.noteitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='note.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inv',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='note.product'),
        ),
    ]
