# Generated by Django 4.0.1 on 2022-04-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_name',
            new_name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.ManyToManyField(default=1, to='note.ClientType'),
        ),
    ]
