# Generated by Django 4.0.1 on 2022-04-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_clienttype_location_rename_client_name_client_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.ManyToManyField(to='note.ClientType'),
        ),
    ]
