# Generated by Django 4.0.1 on 2022-04-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_note_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv',
            name='item',
            field=models.PositiveIntegerField(),
        ),
    ]
