# Generated by Django 4.0.1 on 2022-04-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_alter_inv_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv',
            name='item',
            field=models.IntegerField(default=0),
        ),
    ]
