# Generated by Django 4.0.1 on 2022-04-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_alter_inv_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='inv',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='noteitem',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
