# Generated by Django 4.0.1 on 2022-04-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_pr_pritem_sr_sritem_wi_wiitem_wr_writem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invcontrol',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='invcontrol',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invcontrol',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
