# Generated by Django 4.0.1 on 2022-04-17 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0011_rename_created_at_invcontrol_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteitem',
            name='note',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='note.note'),
            preserve_default=False,
        ),
    ]
