# Generated by Django 4.0.4 on 2022-05-30 15:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0014_workinvcontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carat', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='buy_rate',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('carat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.carat')),
            ],
        ),
    ]
