# Generated by Django 4.0.4 on 2022-05-30 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0015_carat_product_buy_rate_product_sell_rate_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carat',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='carats', to='note.carat'),
            preserve_default=False,
        ),
    ]
