# Generated by Django 4.0.4 on 2022-05-30 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0016_product_carat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.carat'),
        ),
    ]
