# Generated by Django 4.0.4 on 2022-06-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0018_alter_carat_carat_alter_cost_carat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteitem',
            old_name='cost',
            new_name='icost',
        ),
        migrations.AddField(
            model_name='noteitem',
            name='pcost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
