# Generated by Django 4.0.4 on 2022-06-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0019_rename_cost_noteitem_icost_noteitem_pcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteitem',
            name='costid',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noteitem',
            name='prate',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=15),
            preserve_default=False,
        ),
    ]
