# Generated by Django 4.0.4 on 2022-07-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0020_noteitem_costid_noteitem_prate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteitem',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='workinvcontrol',
            name='inventory',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
