# Generated by Django 4.0.4 on 2022-07-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0021_alter_noteitem_weight_alter_workinvcontrol_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='invcontrol',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
