# Generated by Django 4.0.1 on 2022-02-03 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAdvance',
            fields=[
                ('customer_advance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_advance_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('customer_order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_order_date', models.DateTimeField(auto_now_add=True)),
                ('customer_order_total_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer_order_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('location_type_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('location_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('reorder_level', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erm.collection')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('purchase_order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('purchase_order_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_order_total_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('purchase_order_total_items', models.IntegerField()),
                ('purchase_order_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sales_date', models.DateTimeField(auto_now_add=True)),
                ('sales_total_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('advance_payment', models.DecimalField(decimal_places=2, max_digits=9)),
                ('balance_payment', models.DecimalField(decimal_places=2, max_digits=9)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erm.customerorder')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('store', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_item_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sales_item_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erm.product')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erm.sales')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_item_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('purchase_order_item_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erm.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erm.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erm.locationtype')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erm.store')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('from_source', models.CharField(max_length=10)),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erm.store')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erm.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erm.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_order_item_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer_order_item_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erm.customerorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erm.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAdvanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_advance_item_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer_advance_item_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erm.product')),
                ('customer_advance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erm.customeradvance')),
            ],
        ),
        migrations.AddField(
            model_name='customeradvance',
            name='customer_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erm.customerorder'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
