# Generated by Django 4.0.1 on 2022-02-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0003_alter_purchaseorder_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.CharField(max_length=10),
        ),
    ]
