# Generated by Django 4.0.1 on 2022-02-11 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0005_alter_purchaseorder_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='erm.purchaseorder'),
        ),
    ]
