# Generated by Django 4.0.1 on 2022-04-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0007_purchaseorderitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_order_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_order_total_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_order_total_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
