# Generated by Django 4.0.1 on 2022-04-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0008_alter_purchaseorder_purchase_order_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clienttype', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='client_type',
            field=models.ManyToManyField(to='erm.ClientType'),
        ),
    ]
